### ISSUE TITLE
Add new logos to the customers page

### ISSUE THREAD

**Issue by arikfr** [getredash/website#107]
* Atlassian (logo can be found at: https://atlassian.design)
* Datree (datree.io)

**Comment by shimont** [comment]
![datree_logo flat v black background](https://user-images.githubusercontent.com/2613168/45165879-676ff480-b1fe-11e8-95b9-f3c9351ed550.jpg)

![datree_logo flat h black background](https://user-images.githubusercontent.com/2613168/45165909-722a8980-b1fe-11e8-8b53-e4c1a129b967.jpg)

**Comment by shimont** [comment]
![datree_logo flat h](https://user-images.githubusercontent.com/2613168/45165983-a00fce00-b1fe-11e8-8724-da68f0e90d15.jpg)
![datree_logo flat v](https://user-images.githubusercontent.com/2613168/45165999-a56d1880-b1fe-11e8-8f03-a6e30af50acb.jpg)

**Comment by kocsmy** [comment]
Thanks, @shimont and @arikfr — I'll add these quickly. 

@shimont If you'd like to provide a quote here: https://redash.io/customers/ that'd be fantastic. Or we're in the process of creating case studies which are longer and more detailed -- if you want to share how you use Redash, that'd be great!

**Comment by shimont** [comment]
Would love to work on a quote and a use case - could you please contact me via email?
Thanks
