### ISSUE TITLE
Add Cloudron as installation option

### ISSUE THREAD

**Issue by gramakri** [getredash/website#112]
Hi Redash team,
We have been maintaining a redash package for Cloudron for a while now at https://git.cloudron.io/cloudron/redash-app. This app was initially contributed to us by Domenic. We have automated browser tests for testing installs and updates as well in the tests/ directory. There's a demo at https://my-demo.cloudron.me (username: redash password: redash) if you want to see how redash works on Cloudron.

Would be great if you could add Cloudron as an installation method in your docs. Thanks!

**Comment by arikfr** [comment]
Hi,

Thank you for taking the effort to update the documentation, but unfortunately we won't merge this.

Setting up Redash with Cloudron is not simpler than setting up with our own setup script or ready images. But once users do install it with Cloudron they will encounter issues with maintenance and upgrades, as non of our official guides applicable to your deployment type. We seen this scenario happen with Bitnami images, and hence encourage users not to use them.

Anyway, if someone already using your platform for other apps, they can easily find Redash there and I imagine they will try it first before reaching out to our setup guide.

I'm closing the issue, but you're welcome to keep to follow up and keep the discussion.

**Comment by gramakri** [comment]
2 years later, we are still keeping redash up to date at https://git.cloudron.io/cloudron/redash-app and bitnami is closed down :-) I hope you can reconsider.
