### ISSUE TITLE
Broken link to query syntax documentation

### ISSUE THREAD

**Issue by justinclift** [getredash/website#175]
While looking around for info on how to transform textual date strings into a date/time format Redash can use, this 404 link in the current docs became apparent:

![redash-2019 01 23-broken_link 1](https://user-images.githubusercontent.com/406299/51579886-ba7ce680-1f16-11e9-91e3-a30a27cf5b59.png)

![redash-2019 01 23-broken_link 2](https://user-images.githubusercontent.com/406299/51579536-6b828180-1f15-11e9-8039-b5f11b528e79.png)

The page with the broken link:

&nbsp; &nbsp; https://redash.io/help/user-guide/querying/writing-queries#Query-Syntax

The 404 link page:

&nbsp; &nbsp; https://redash.io/help/data-sources/querying/querying_category

**Comment by arikfr** [comment]
Thanks! Fixed :)
