### ISSUE TITLE
Admin Guide: env vars being incorrect displayed

### ISSUE THREAD

**Issue by jeffersfp** [getredash/website#187]
At [https://redash.io/help/open-source/admin-guide/env-vars-settings](https://redash.io/help/open-source/admin-guide/env-vars-settings), env vars are being incorrectly displayed due to Markdown rendering, using the underscores from the vars names to make them italic:

![image](https://user-images.githubusercontent.com/8990515/51949031-08f81c80-2412-11e9-85e7-561792b74b47.png)

**Comment by jeffersfp** [comment]
PR #188 should fix it. :)

**Comment by arikfr** [comment]
Fixed in #188. Thanks!
