### ISSUE TITLE
Top menu "Help" dropdown click target

### ISSUE THREAD

**Issue by susodapop** [getredash/website#221]
The `Help` menu on the navbar is a dropdown. At the moment I need to click on the font glyphs to invoke the menu; but this isn't obvious. When I hover over the `<div>` the entire thing changes its `background` color which makes me think that I can click anywhere on the element to invoke the menu. Alternatively, it looks like I need to click the down arrow to invoke the menu -- but this is hard to get exactly right with a mouse because the arrow is so small.

In this ten second GIF I demonstrate the three behaviors:
1. Clicking on the word "Help" invokes the menu
2. Clicking in blankspace on the `<div>` does nothing
3. Clicking on the tiny down arrow invokes the menu

![ScreenFlow](https://user-images.githubusercontent.com/17067911/54278377-2fa48980-4560-11e9-961d-74278b5d4849.gif)

Can we change this to either make the down arrow bigger or even better: invoke the dropdown menu whenever the user clicks the entire `<div>`?

**Comment by ranbena** [comment]
@susodapop fixed. Give it a spin.

**Comment by susodapop** [comment]
It works great @ranbena! Thanks.
