### ISSUE TITLE
Non-existent JSON loading feature is documented for URL datasource

### ISSUE THREAD

**Issue by pasky** [getredash/website#228]
The URL datasource documentation documents a JSON datasource option that can process an arbitrary JSON (which would be awesome). We just spent 20 minutes trying to figure out how to use it and in fact didn't find any traces of such support in the redash codebase at all.

**Comment by susodapop** [comment]
This feature is new in the most recent release of Redash. It has not yet migrated down to the Open Source version. There's a discussion about this on [the user forum](https://discuss.redash.io/t/missing-json-data-source/3448/21) that will be updated when the JSON data source is made available in the Open Source version.

**Comment by pasky** [comment]
Oh I see. It's a bit confusing that this repo is documenting only the paid version. :) Maybe it should be mentioned on the page?

(BTW, is there a way to run the non-open-source version on premise or is that restricted to the cloud hosting?)

**Comment by susodapop** [comment]
There isn't exactly a "paid" version of Redash versus an open-source version. The two products have 1-to-1 feature parity for the most part. This is a question of logistics more than strategy. But I can see how confusing this would be and will add a note to the docs to reflect the temporary divergence of feature-set.
