### ISSUE TITLE
Website does not load sometimes

### ISSUE THREAD

**Issue by kocsmy** [getredash/website#244]
I bumped into this twice so far (and I'm not visiting it too often), that the marketing site won't load:

![image](https://user-images.githubusercontent.com/2378022/58569159-ddf1ce00-8235-11e9-8e52-2402793ba856.png)

![image](https://user-images.githubusercontent.com/2378022/58569183-ea762680-8235-11e9-8474-59ac9f896d59.png)

Refresh resolved the issue though. I'd add a critical flag to this.

**Comment by susodapop** [comment]
Do we use something like down detector for the public site? Could this be a Netlify issue?

**Comment by susodapop** [comment]
I've actually just had the same thing happen in Safari 12.0.3 I'm not able to recreate it though. This was after manually typing `redash.io/help` into my URL bar (I didn't click a link). I'll try to recreate. Here's my screenshots.

![Screen Shot 2019-05-29 at 19 46 03](https://user-images.githubusercontent.com/17067911/58600511-80b44780-824a-11e9-85ed-4d67f97fcbaf.png)
![Screen Shot 2019-05-29 at 19 46 00](https://user-images.githubusercontent.com/17067911/58600515-8873ec00-824a-11e9-929f-1e73154ce419.png)

**Comment by ranbena** [comment]
@arikfr I'm still getting this error. I think you need to remove `gatsby-plugin-manifest` as well.

**Comment by ranbena** [comment]
Worked.
