### ISSUE TITLE
BigQuery setup documentation mentions non-existent permission

### ISSUE THREAD

**Issue by shosti** [getredash/website#251]
In https://redash.io/help/data-sources/setup/bigquery#BigQuery-Permissions-and-Roles, it lists `bigquery.datasets.list` as a required permission, but that permission doesn't exist in GCP (see https://cloud.google.com/bigquery/docs/access-control).

**Comment by susodapop** [comment]
Thanks for your feedback @shosti! I've opened a PR to address this.
