### ISSUE TITLE
Missing image in User Guide -> Permissions & Groups page

### ISSUE THREAD

**Issue by justinclift** [getredash/website#258]
Reading through the [Permissions & Groups page](https://redash.io/help/user-guide/users/permissions-groups) in our User Guide, a text fragment says:

```
The screenshot shown below shows a Dashboard Widget with a visualization the
user doesn’t have access to.
```

Unfortunately, there's no screenshot on the page. :wink:

We should either nuke that line of text, or (better) add an appropriate screenshot. :smile:

**Comment by ranbena** [comment]
@susodapop?

**Comment by susodapop** [comment]
According to git history, this has been missing since March of 2018l. Here's what the image was. I'll recreate this since the UI has changed **a lot** since then. 
![restricted_dashboard](https://user-images.githubusercontent.com/17067911/60552757-c2c32400-9cf5-11e9-926c-cf8dfc0a8806.png)
