### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by rockwotj** [getredash/website#26]
I am unable to contribute to repositories without a license, can you add one? I'm hoping to add new features and would like to add documentation when I do so.

**Comment by arikfr** [comment]
Done. 👍

**Comment by arikfr** [comment]
Would love to hear what features you had in mind :)

**Comment by rockwotj** [comment]
Thanks!

https://github.com/getredash/redash/pull/1504 is the first, after that there are more with parameters that we'd like to have. Enum support for parameters is one off the top of my head. I'll open up feature requests for them before I start anything and discuss on the appropriate channels.
