### ISSUE TITLE
Add documentation for ISO 8601 Dates with MongoDB Queries

### ISSUE THREAD

**Issue by susodapop** [getredash/website#261]
If you try to pass a datetime parameter to MongoDB it will never match properly because there is currently a mismatch between the format we provide and what MongoDB expects. You can remedy this by wrapping the parameter value with the `$humanTime` extension, i.e.: `{"$humanTime": "{{ param }}"}` where you would use just `"{{param}}"`.

**Comment by justinclift** [comment]
Should this be closed, as the PR to fix it has been merged?
