### ISSUE TITLE
Opening slide for video guides

### ISSUE THREAD

**Issue by arikfr** [getredash/website#272]
We're about to produce a few video guide and need an opening slide for them, to use when giving an intro to the video and as a preview screenshot in Youtube.

The slide should contain:

* Redash logo
* Video title
* (optional) Preview image

**Comment by ranbena** [comment]
Here's what I worked on in youtube context:

### Preview
![youtube](https://user-images.githubusercontent.com/486954/61205446-bcbb4300-a6f8-11e9-844e-d1fd1a779ff3.jpg)

### Intro slide
![youtube2](https://user-images.githubusercontent.com/486954/61205447-bd53d980-a6f8-11e9-9e26-fcc916146f09.jpg)

### Preview image slide
TBD

**Comment by arikfr** [comment]
Looking good! I would change the font in the "Intro slide". It doesn't give the same polished vibe as the background or the logo.

**Comment by susodapop** [comment]
I love the inclusion of the documentation link with these designs. Where would we put a screencap of a visualization?

**Comment by susodapop** [comment]
Another nice to have would be an "outro" slide with links to our website, our discussion forum, and the github repo.

**Comment by ranbena** [comment]
How do you feel about these?

## Option 1
<img src="https://user-images.githubusercontent.com/486954/61612927-93eefc80-ac68-11e9-82c6-f1daf8188a30.jpg" />

## Option 2
![intro2](https://user-images.githubusercontent.com/486954/61612928-93eefc80-ac68-11e9-8c00-266891a01333.jpg)

**Comment by arikfr** [comment]
My first reaction was: they are good, but I feel like they have a different design language than our current material. 

But now that I look at the first iteration it looks dull and boring... so maybe the new Option 1, but with a logo?

**Comment by ranbena** [comment]
I don't think our product's design should have any affect on the video look and feel.

Nevertheless, here's option 1 with logo:

![intro-slide](https://user-images.githubusercontent.com/486954/61616696-d6690700-ac71-11e9-9781-6f2119863f12.jpg)

**Comment by arikfr** [comment]
And if we want to put a screenshot we will replace the illustration with it?

**Comment by ranbena** [comment]
> And if we want to put a screenshot we will replace the illustration with it?

That would be too small I think.

But I'm not sure it's relevant. [This is how I see the intro](https://drive.google.com/open?id=1xff4JcKjGfwD6ypTLsjgLspd9SsgpmgX).

**Comment by arikfr** [comment]
:thinking: I'm not sure we should switch out from this slide until he introduces the table. When you show someone doing something, people try to follow. It's not really clear that this is the "trailer" for the rest of it.

The reason for the image is to easily get a sense of what the video is about without looking at the text. Makes sense?

**Comment by ranbena** [comment]
>  I'm not sure we should switch out from this slide until he introduces the table. When you show someone doing something, people try to follow. It's not really clear that this is the "trailer" for the rest of it.

Yeah I get that.

> The reason for the image is to easily get a sense of what the video is about without looking at the text. Makes sense?

I couldn't make it work 😣Will revise.

**Comment by arikfr** [comment]
Let's keep as is then (without the image) and move on.

**Comment by susodapop** [comment]
@ranbena LGTM. I'll proceed using option 1.

Two items:
* Can you send this to me at 2560x1440 resolution?
* Which font do you use for the video title ("Creating Visualizations & Dashboards")? I add these after the fact in my video editor (Screenflow).

**Comment by ranbena** [comment]
@susodapop I'm preparing all screens in editable html pages hosted at codesandbox, so all you'll have to do is type in the title and take a fullscreen screenshot.

**Comment by ranbena** [comment]
Intro: https://z2357.codesandbox.io/

**Comment by ranbena** [comment]
Thumbnail: https://n3sb9.codesandbox.io/

**Comment by ranbena** [comment]
> Another nice-to-have would be an "outro" slide with links to our website, our discussion forum, and the github repo.


![outro](https://user-images.githubusercontent.com/486954/61700409-544a1280-ad45-11e9-9166-f7ef94ac6eca.png)

Looks too much like a presentation outro. Suggestions welcome.
[Full quality image](https://drive.google.com/open?id=1rWFUgi2AWimedXJZXZcDu76QF-0iP7s7)

**Comment by susodapop** [comment]
Can you update the Thumbnail to text-align right? For longer titles, the video title crosses into the blue-ish stripe on the right. Can it dynamically change alignment to ensure it never overflows to the right?

**Comment by ranbena** [comment]
> Can you update the Thumbnail to text-align right? For longer titles, the video title crosses into the blue-ish stripe on the right. Can it dynamically change alignment to ensure it never overflows to the right?

Since the text has to have a curve to it - you gotta type in line breaks followed by spaces for it to come out right.

<img width="853" alt="Screen Shot 2019-07-23 at 15 38 43" src="https://user-images.githubusercontent.com/486954/61712908-05f63d00-ad60-11e9-9f6f-d4cbc4442d4e.png">

**Comment by ranbena** [comment]
@susodapop the font is Roboto which you might not have on your system - I added it now to the pages.

**Comment by kravets-levko** [comment]
@ranbena I'm not sure how can I edit your sandboxes, so will put it here. Add a `<div>` as a first child of `<div id="text">` and add this CSS to it:
```css
div {
  float: left;
  shape-outside: polygon(0 0, 360px 0, 660px 720px, 0 720px);
  width: 660px;
  height: 720px;
}
```
You'll also need to adjust other elements a bit, but I think it’s worth it. It will work fine in [Chrome and FF](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside)

**Comment by ranbena** [comment]
Ohhh that's niiiice!

**Comment by ranbena** [comment]
Not sure I can let you edit but for sure you can fork @kravets-levko 
https://codesandbox.io/s/redash-video-thumbnail-n3sb9?fontsize=14

**Comment by susodapop** [comment]
10-4 on the character spacing. I apparently didn't have Roboto locally -- I'll re-render the opening slide for our one existing video and re-upload.

**Comment by kravets-levko** [comment]
@ranbena @susodapop https://hx0e7.codesandbox.io/

**Comment by susodapop** [comment]
> intro: https://z2357.codesandbox.io/

Hey @ranbena this absolutely doesn't render at 1280x720 for me. It's 1278 x ~800. I'm having to manually crop in the image editor.

**Comment by ranbena** [comment]
Totally right!
Updated to height to 720 but I do see width as 1280.
