### ISSUE TITLE
Missing example in "Date Range Parameters"

### ISSUE THREAD

**Issue by justinclift** [getredash/website#277]
Just noticed our "[Data Range Parameters](https://redash.io/help/user-guide/querying/query-parameters#Date-Range-Parameters)" doc is missing the example piece:

```
You will typically need to separate them in your query (into different
`WHERE` clauses, e.g.).
```

**Comment by susodapop** [comment]
@justinclift I opened a PR with an example added. Will merge pending your review.

**Comment by justinclift** [comment]
Thanks @susodapop.  Will look at it shortly. :smile:
