### ISSUE TITLE
Need a way to manual push to algolia index

### ISSUE THREAD

**Issue by susodapop** [getredash/website#296]
Right now we trust Algolia to index and find everything. Sometimes it fails. Like a search for "IP address" should return the page with our SaaS IP Address. But it doesn't.

**Comment by arikfr** [comment]
I took a look and apparently we were sending to Algolia either the article's description (only one or two had those) or a 140 char excerpt along with the category and titles in the article. :man_facepalming:  This explains why sometimes it seemed to find stuff but most of the time it didn't.

#304 fixes indexing. Once indexing was fixed we had another issue where it would show the full article in the search results, this was resolved in #317 by switching to showing the snippet of the content.

@susodapop give the search a try now and see if it still feels like it should be improved.

**Comment by susodapop** [comment]
Seems great from my testing this week. Thanks!
