### ISSUE TITLE
Fix dead links in the user guide

### ISSUE THREAD

**Issue by arikfr** [getredash/website#3]
Error	URL	Anchor Text	Linked From
404	https://redash.io/help/queries/writing_queries.md	How to Schedule a Query?	https://redash.io/help/
404	https://redash.io/help/getting_started/(../aboutrd/aboutrd.md	full list	https://redash.io/help/getting_started/how_to_add_data_sources_to_redash.html
404	https://redash.io/help/dashboards/(visualization/visualization.md	instructions	https://redash.io/help/dashboards/dashboards.html
404	https://redash.io/help/user-mgmt/permissions_and_groups.md	here	https://redash.io/help/user-mgmt/user-mgmt.html
404	https://redash.io/help/queries/how_to_export_query_results_to_csv_or_json.md	export your results to CSV or JSON	https://redash.io/help/queries/query_actions.html
404	https://redash.io/help-onpremise/setup/getting_started/permissions_and_groups.md	Permissions and Groups	https://redash.io/help-onpremise/
404	http://demo.redash.io/saml/callback	http://demo.redash.io/saml/callback	https://redash.io/help-onpremise/setup/saml-authentication-and-authorization.html
404	https://redash.io/help-onpremise/setup/maintenance/how-to-upgrade-redash.md	upgrade process	https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
404	https://redash.io/help-onpremise/setup/setup/how-to-create-a-google-developers-project.md	instructions	https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
404	https://redash.io/help-onpremise/setup/setup/supported-data-sources.md	documentation	https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
404	https://redash.io/help-onpremise/setup/setup/settings-environment-variables.md	settings article	https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
404	https://redash.io/help-onpremise/setup/setup/ssl-https-setup.md	instructions	https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
404	https://redash.io/help-onpremise/setup/user-guide/queries/querying_mongodb.md	documentation	https://redash.io/help-onpremise/setup/supported-data-sources-options-reqs.html
404	https://redash.io/help-onpremise/setup/user-guide/queries/querying_elasticsearch.md	documentation	https://redash.io/help-onpremise/setup/supported-data-sources-options-reqs.html
404	https://redash.io/help-onpremise/setup/how-rd-works/data-source-results-format.md	results JSON format	https://redash.io/help-onpremise/setup/supported-data-sources-options-reqs.html
404	https://redash.io/help-onpremise/setup/user-guide/queries/querying_jira_jql.md	here	https://redash.io/help-onpremise/setup/supported-data-sources-options-reqs.html

**Comment by afoonalex** [comment]
should be ok now - can you rerun this script and let me know if I missed anything/

**Comment by arikfr** [comment]
This is the tool I used: http://www.deadlinkchecker.com/website-dead-link-checker.asp

This is what it found this time:

404 Not Found	https://redash.io/help/getting_started/(../queries/writing_queries.md	click here
404 Not Found	https://redash.io/help/setup/supported-data-sources.html	documentation
