### ISSUE TITLE
Developer Installation Guide

### ISSUE THREAD

**Issue by r-nyq** [getredash/website#328]
The [Developer Installation Guide](https://redash.io/help/open-source/dev-guide/setup) is still suggesting the user to use Python 2.7 and Celery, both which are not true anymore.

**Comment by susodapop** [comment]
The Python 3 and RQ migrations haven’t been released yet. We’ll update the docs when the development work is done. For now, the docs are “up to date” since we don’t recommend running the master branch in production. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by r-nyq** [comment]
I see. My misunderstanding about the release.

**Comment by arikfr** [comment]
Actually, considering the development guide is for developing the project, it's need to be in-sync with master.

Thank you, @r-nyq for bringing this to attention. The Python 3/RQ migrations were a huge effort that we didn't tie up all the loose ends yet.

**Comment by arikfr** [comment]
I've created an update to the documentation. You can see a preview here: https://deploy-preview-331--redashio.netlify.com/help/open-source/dev-guide/setup.

If you have the chance, please give it a look and let me know if it makes things clearer. 

Thanks.

**Comment by r-nyq** [comment]
Great. Thanks!
