### ISSUE TITLE
Explain how to get the spreadsheet ID

### ISSUE THREAD

**Issue by arikfr** [getredash/website#45]
> So for example, if the spreadsheet URL is:
https://docs.google.com/spreadsheets/d/1DFuuOMFzNoFQ5EJ2JE2zB79-0uR5zVKvc0EikmvnDgk/edit#gid=0
> 
> Then the id will be `1DFuuOMFzNoFQ5EJ2JE2zB79-0uR5zVKvc0EikmvnDgk`.

**Comment by fabform** [comment]
This is very handy to find the google sheet id
[how to find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by susodapop** [comment]
Thanks @fabform this is now covered in the docs [here](https://redash.io/help/data-sources/querying/google-sheets):

<img width="770" alt="CleanShot 2022-01-10 at 12 12 52@2x" src="https://user-images.githubusercontent.com/17067911/148817274-22a2c5b5-ea44-42b8-9458-24dc3f1565c0.png">
