### ISSUE TITLE
Inconsistent documentation for using parameters in query via API

### ISSUE THREAD

**Issue by phillipjohnson** [getredash/website#486]
I've located three different methods suggested to sent parameters to a query using the API.
## Redash User Guide
**Link:** https://redash.io/help/user-guide/integrations-and-api/api
**Documented method:** `parameters` JSON object in `POST` body (as object)
```js
{ 
    "parameters": {
    	"number_param": 100,
    	"date_param": "2020-01-01",
    	"date_range_param": {
    		"start": "2020-01-01",
    		"end": "2020-12-31"
    		}
    	}
    }
```
## Redash Forums
**Link:** https://discuss.redash.io/t/queries-with-parameters-unable-to-use-api-call/4614/4
**Documented method:** `parameters` JSON object in `POST` body (as list)
```js
{
  "parameters": [
    {
      "param": 1
    }
  ]
}
```
## Redash Toolbelt
**Link:** https://github.com/getredash/redash-toolbelt/blob/master/redash_toolbelt/examples/refresh_query.py
**Documented method:** Query-string parameters
```python
s.post('{}/api/queries/{}/refresh'.format(redash_url, query_id), params=params)
```

If these are all allowed, they should all be documented (although the different format of the `parameters` is suspect). For what it is worth, I only had success with the last option (query string).

**Comment by arikfr** [comment]
Thank you for reporting this! We will review these and make sure they are both accurate and consistent.

As for the third one - the refresh one: it's an API we need to deprecate and indeed it might behave differently.

**Comment by arikfr** [comment]
@susodapop

**Comment by susodapop** [comment]
**Redash user guide**: this is correct.
**Redash forums**: I edited the comment.
**Redash Toolbelt**: Fixed the example script to follow the user guide [here](https://github.com/getredash/redash-toolbelt/pull/35)
