### ISSUE TITLE
Make a parameter with static value explicit

### ISSUE THREAD

**Issue by rodrigowirth** [getredash/website#561]
### Example

In the following example, we have a Widget with two parameters. One of them is a Widget Parameter, as the other one is a Static Value.
![image](https://user-images.githubusercontent.com/5023665/114224062-f4dfcc00-9946-11eb-997c-fbecf989c737.png)

In this case, only the Widget Parameter is presented for the user.
![image](https://user-images.githubusercontent.com/5023665/114224433-70417d80-9947-11eb-9a69-2cc6d96dfe11.png)

If we add the same query, twice or more into the dashboard, but with different Static Value parameters, it's not possible to understand the difference between them.
![image](https://user-images.githubusercontent.com/5023665/114224552-99620e00-9947-11eb-8689-072ad88ba52f.png)

### Suggestion
Make the static value explicit in the Widget
![image](https://user-images.githubusercontent.com/5023665/114224764-e0e89a00-9947-11eb-8fa1-0b0ac70f4686.png)

**Comment by susodapop** [comment]
This is our documentation repository. Can you instead direct this to our user forum as a feature request? Thanks!
