### ISSUE TITLE
website images redirect to http://help.redash.io/

### ISSUE THREAD

**Issue by selmertsx** [getredash/website#60]
I can't find any images in redash website. 
http://help.redash.io/article/61-creating-a-dashboard

![2017-12-20 7 44 03](https://user-images.githubusercontent.com/1563239/34203358-2647648c-e5be-11e7-9787-1f663408926c.png)

These images are redirect to `http://help.redash.io/`

```
➜  ~ curl https://redash.io/help/assets/gifs/dashboards/Dashboards.gif
Redirecting to http://help.redash.io/
```

**Comment by arikfr** [comment]
Which page is the screenshot from?

**Comment by selmertsx** [comment]
This page.
- http://help.redash.io/article/61-creating-a-dashboard


There are no images in below pages too.

- http://help.redash.io/article/67-setting-up-an-alert
- http://help.redash.io/article/73-permissions-groups
- http://help.redash.io/article/127-api-access

**Comment by ak64th** [comment]
I encountered the same issue. It seems some images are served from `59005a708ebdd932a2ed5f47--redashio.netlify.com` and some are not.

**Comment by arikfr** [comment]
I updated the redirect settings to exclude images.

Thank you for bringing this up!
