### ISSUE TITLE
Bump Gatsby from 2.0.91 to 5

### ISSUE THREAD

**Issue by masayuki038** [getredash/website#684]
I tried to bump gatsby-transformer-remark from 2.1.17 to 5.25.1 manually at https://github.com/getredash/website/pull/662. However, it failed. It looks like we should bump node version before this.

Then I tried to bump node version to 16 in my local. However, it failed to install `sharp`. It looks like this depends on node version.

The version of gatsby is 2.0.91 in this website. It looks like the current stable version is 5.12. We should try to bump it to 5.12 or higher and bump node version to 16 or 18.

![image](https://github.com/getredash/website/assets/36331/08195c63-a8e9-4416-92a6-2e20350d2a76)

**Comment by lucydodo** [comment]
Close this PR because the related PRs(https://github.com/getredash/website/pull/703) have been merged.
